= Relaton for IHO documents

image:https://img.shields.io/gem/v/relaton-iho.svg["Gem Version", link="https://rubygems.org/gems/relaton-iho"]
image:https://github.com/relaton/relaton-iho/workflows/macos/badge.svg["Build Status (macOS)", link="https://github.com/relaton/relaton-iho/actions?workflow=macos"]
image:https://github.com/relaton/relaton-iho/workflows/windows/badge.svg["Build Status (Windows)", link="https://github.com/relaton/relaton-iho/actions?workflow=windows"]
image:https://github.com/relaton/relaton-iho/workflows/ubuntu/badge.svg["Build Status (Ubuntu)", link="https://github.com/relaton/relaton-iho/actions?workflow=ubuntu"]
image:https://codeclimate.com/github/relaton/relaton-iho/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/relaton/relaton-iho"]
image:https://img.shields.io/github/issues-pr-raw/relaton/relaton-iho.svg["Pull Requests", link="https://github.com/relaton/relaton-iho/pulls"]
image:https://img.shields.io/github/commits-since/relaton/relaton-iho/latest.svg["Commits since latest",link="https://github.com/relaton/relaton-iho/releases"]

RelatonIho is a Ruby gem that implements the https://github.com/metanorma/metanorma-model-iso#iso-bibliographic-item[IsoBibliographicItem model].

It currently retrieves metadata of IHO Standards from https://github.com/relaton/relaton-data-iho.

== Installation

Add this line to your application's Gemfile:

[source,ruby]
----
gem 'relaton-iho'
----

And then execute:

[source,sh]
----
$ bundle
----

Or install it yourself as:

[source,sh]
----
$ gem install relaton-iho
----

== Usage

=== Search for a standard using keywords

Reference can be specified with or without an edition. References without an edition will return the latest edition of the standard. References with an edition will return the standard with the specified edition.

[source,ruby]
----
require 'relaton_iho'
=> true

# Search for a standard using a reference without an edition
item = RelatonIho::IhoBibliography.search("IHO B-11")
[relaton-iho] (IHO B-11) Fetching from Relaton repository ...
[relaton-iho] (IHO B-11) Found: `B-11`
=> #<RelatonIho::IhoBibliographicItem:0x007fe74fc80800
...

# Search for a standard using a reference with an edition
item = RelatonIho::IhoBibliography.search("IHO B-11 1.0.0")
[relaton-iho] (IHO B-11 1.0.0) Fetchint from Rlaont repository ...
[relaton-iho] (IHO B-11 1.0.0) Found: `B-11`
=> #<RelatonIho::IhoBibliographicItem:0x00007fe79d0ed698
...
----

=== XML serialization
[source,ruby]
----
item.to_xml
=> "<bibitem id="B-11" type="standard" schema-version="v1.2.1">
      <fetched>2022-12-04</fetched>
      <title type="main" format="text/plain" language="en">IHO-IOC GEBCO Cook Book</title>
      <title type="main" format="text/plain" language="fr">Livre de recettes GEBCO OHI-COI</title>
      <uri type="pdf">https://www.star.nesdis.noaa.gov/socd/lsa/GEBCO_Cookbook/documents/CookBook_20191031.pdf</uri>
      <docidentifier type="IHO" primary="true">B-11</docidentifier>
      ...
    </bibitem>"
----
With argument `bibdata: true` it outputs XML wrapped by `bibdata` element and adds flavor `ext` element.
[source,ruby]
----
item.to_xml bibdata: true
=> "<bibdata type="standard" schema-version="v1.2.1">
      <fetched>2022-12-04</fetched>
      <title type="main" format="text/plain" language="en">IHO-IOC GEBCO Cook Book</title>
      <title type="main" format="text/plain" language="fr">Livre de recettes GEBCO OHI-COI</title>
      <uri type="pdf">https://www.star.nesdis.noaa.gov/socd/lsa/GEBCO_Cookbook/documents/CookBook_20191031.pdf</uri>
      <docidentifier type="IHO" primary="true">B-11</docidentifier
      ...
      <ext schema-version="v1.0.0">
        ...
      </ext>
    </bibdata>"
----

=== Get code
[source,ruby]
----
RelatonIho::IhoBibliography.get "IHO B-11"
[relaton-iho] (IHO B-11) Fetching from Relaton repository ...
[relaton-iho] (IHO B-11) Found: `B-11`
=> #<RelatonIho::IhoBibliographicItem:0x007fe78dbb7c78
...
----

=== Typed links

Each IHO document has `html`, `website`, or `pdf` type link.

[source,ruby]
----
item.link
=> [#<RelatonBib::TypedUri:0x00007fb5162d1478 @content=#<Addressable::URI:0x8c0 URI:https://www.star.nesdis.noaa.gov/socd/lsa/GEBCO_Cookbook/documents/CookBook_20191031.pdf>, @type="pdf">]
----

=== Create bibliographic item from XML
[source,ruby]
----
RelatonIho::XMLParser.from_xml File.read('spec/fixtures/iho.xml')
=> #<RelatonIho::IhoBibliographicItem:0x007fc322ea82c8
...
----

=== Create bibliographic item from YAML
[source,ruby]
----
hash = YAML.load_file 'spec/fixtures/iho.yaml'
=> {"id"=>"B-11",
...

RelatonIho::IhoBibliographicItem.from_hash hash
=> #<RelatonIho::IhoBibliographicItem:0x007fc322ef8548
...
----

=== Logging

RelatonIho uses the relaton-logger gem for logging. By default, it logs to STDOUT. To change the log levels and add other loggers, read the https://github.com/relaton/relaton-logger#usage[relaton-logger] documentation.

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run `rake spec` to run the tests. You can also run `bin/console` for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To release a new version, update the version number in `version.rb`, and then run `bundle exec rake release`, which will create a git tag for the version, push git commits and tags, and push the `.gem` file to https://rubygems.org[rubygems.org].

== Contributing

Bug reports and pull requests are welcome on GitHub at https://github.com/relaton/relaton-iho.

== License

The gem is available as open source under the terms of the https://opensource.org/licenses/MIT[MIT License].
